import time
f1=open("A10.txt","r")
obj1=f1.tell()
print("Current File Pointer is:",obj1)
print()
obj2=f1.read(19)
print("Current File Pointer is:",obj2)
print()
obj3=f1.tell()
print('Current File Pointer is:',obj3)
print()
obj4=f1.seek(0)
print("Current File Pointer is:",obj4)
print()
obj5=f1.read(19)
print("Current File Pointer is:",obj5)
print()
f1.close()
print()
time.sleep(2)
print("End of an application")