import time
# f1=open("A1.txt","r")
# f1=open("A1.txt","w")
f1=open("A1.txt")
print("===File Information===")
print("File name is:",f1.name)
print("File_mode is:",f1.mode)
print("File_Closed is:",f1.closed)
print("File is readable:",f1.readable())
print("File is writable:",f1.writable())
print()
f1.close()
print()
time.sleep(2)
print("End of an application")
