import time
f1=open("A10.txt","r")
res1=f1.tell()
print("Current File_Pointer position is:",res1)
print()
res2=f1.read(19)
print(res2)
print()
res3=f1.tell()
print("Current File_pointer Position is:",res3)
print()
f1.close()
print()
time.sleep(2)
print("End of an application")