import time
f2=open("A2.txt","w")
f2.write("Bharath\n")
f2.write("Satish\n")
f2.write("Vinay\n")
f2.write("Ankit\n")
f2.write("Homeshwar\n")
print()
print("A new file is created with it;s content successfully")
print()
f2.close()
print()
time.sleep(2)
print("End of an application")